### ISSUE TITLE
Polishing the App

### ISSUE THREAD

**Issue by jamesnyakush** [MosesWangira/DSC_KIBABII_UNIVERSITY#7]
We need to add the following

1. Firebase Auth.
2. Firebase database.
3. App Theme.
4. Design Pattern (MVVM).
5. Dependency Injection.

**Comment by MosesWangira** [comment]
will be working on firebase auth weekend

**Comment by jamesnyakush** [comment]
Great Awesome cant wait to deep dive into the system
